import { useConflictSummary } from '../hooks/useConflictSummary'

export default function SummaryTile({
  conflictId,
  countryId,
  conflictName,
  countryName,
}: {
  conflictId: number
  countryId?: number
  conflictName?: string | null
  countryName?: string | null
}) {
  const { data, isLoading, error } = useConflictSummary(conflictId, countryId, { conflictName, countryName })

  if (isLoading) return <div className="p-3 text-sm">Generating summary858585</div>
  if (error) return <div className="p-3 text-sm text-red-600">Failed to load summary</div>
  if (!data?.summary) return <div className="p-3 text-sm">No summary available.</div>

  return (
    <div className="flex h-full flex-col p-3 overflow-y-auto text-sm leading-relaxed text-gray-800">
      <div className="text-xs text-gray-500 mb-2">
        Conflict summary
        {data.cached ? ' (cached)' : ''}
      </div>
      <div className="whitespace-pre-line">{data.summary}</div>
      <div className="mt-3 text-[10px] text-gray-400">
        Generated by AI ({data.model})
      </div>
    </div>
  )
}
